#主配置文件

spring:
  # 文件编码 UTF8
  mandatory-file-encoding: UTF-8
  mvc:
    # 404 交给异常处理器处理
    throw-exception-if-no-handler-found: true
  web:
    resources:
      # 关闭默认静态资源的映射规则
      add-mappings: false

  # 数据源配置，请修改为你项目的实际配置
  datasource:
    username: ${RDS_USER_NAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${RDS_ADDRESS}:${RDS_PORT}/${RDS_DB_NAME}?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8

mybatis-plus:
  configuration:
    # 开启下划线转驼峰
    map-underscore-to-camel-case: true
    # 指定默认枚举类型的类型转换器
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    # 开启/关闭 banner 打印
    banner: false
    db-config:
      # 逻辑删除（软删除）
      logic-delete-value: NOW()
      logic-not-delete-value: 'NULL'
  # mapper路径位置
  mapper-locations: classpath:mapper/*.xml


